export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
export const SET_LOADING = "SET_LOADING";
export const SET_PAGE = "SET_PAGE";
export const SET_FILTERED_TRANSACTIONS = "SET_FILTERED_TRANSACTIONS";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
